export const ADMIN_ROUTES = {
  dashboard: '/admin',
  users: '/admin/utilisatrices',
  content: {
    root: '/admin/contenus',
    articles: '/admin/contenus/articles',
    categories: '/admin/contenus/categories',
    premium: '/admin/contenus/premium',
    media: '/admin/contenus/medias',
  },
  spiritual: {
    root: '/admin/reperes-spirituels',
    articles: '/admin/reperes-spirituels/articles-religieux',
    validations: '/admin/reperes-spirituels/validations',
    hijri: '/admin/reperes-spirituels/calendrier-hijri',
    ramadan: '/admin/reperes-spirituels/ramadan-qadaa',
    nifas: '/admin/reperes-spirituels/nifas',
  },
  notifications: {
    root: '/admin/notifications',
    new: '/admin/notifications/nouvelle',
    scheduled: '/admin/notifications/programmees',
    history: '/admin/notifications/historique',
  },
  subscriptions: {
    root: '/admin/abonnements',
    plans: '/admin/abonnements/plans',
    active: '/admin/abonnements/actifs',
    history: '/admin/abonnements/historique',
    pricing: '/admin/abonnements/tarification-pays',
  },
  exports: '/admin/exports-medicaux',
  support: '/admin/support',
  analytics: '/admin/analytics',
  configuration: {
    root: '/admin/configuration',
    objectives: '/admin/configuration/objectifs',
    flags: '/admin/configuration/feature-flags',
    themes: '/admin/configuration/themes',
    settings: '/admin/configuration/parametres-globaux',
  },
  security: {
    root: '/admin/securite',
    admins: '/admin/securite/administrateurs',
    roles: '/admin/securite/roles-permissions',
    logs: '/admin/securite/journaux-activite',
    privacy: '/admin/securite/demandes-donnees',
  },
} as const;
