import {PDFDocument, StandardFonts, decodeFromBase64, rgb, type PDFFont, type PDFPage} from 'pdf-lib';
import fontkit from '@pdf-lib/fontkit';
import bidiFactory from 'bidi-js';
import type {ExportReportModel} from './medicalExportFormatting';
import {CAIRO_ARABIC_SUBSET_BASE64} from './pdfArabicFont';

// Local, on-device PDF generation for the Medical Export "Rapport de suivi" —
// pure JS (pdf-lib has zero native modules, so no autolinking/Android
// configuration is needed at all), no server, no upload. This is the
// professional-readable history required by the cahier des charges
// ("Création d'un historique clair pour un professionnel de santé"): a
// sober, chronological export of exactly what the user selected — never a
// diagnosis, a risk score, or a "normal/abnormal" judgment.
//
// TEXT RENDERING (M45)
// - Latin / French text keeps using the standard Helvetica face, exactly as
//   before (WinAnsi only): a report without Arabic is generated byte-for-byte
//   the same way and never loads the Arabic font.
// - Arabic text is drawn with an embedded, subset Cairo (OFL, see
//   pdfArabicFont.ts), embedded only when the report actually contains Arabic:
//   * shaping/joining: pdf-lib asks @pdf-lib/fontkit to lay the text out, which
//     applies the font's OpenType joining features (init/medi/fina/isol, ligatures)
//     and returns the glyphs in VISUAL order for right-to-left scripts;
//   * direction: fontkit does not run the Unicode bidirectional algorithm, so
//     bidi-js resolves the embedding levels per line, the runs are reordered
//     visually (UAX #9 rule L2), mirrored characters are swapped in RTL runs,
//     and digits / Latin words stay left-to-right inside Arabic text. Strings are
//     NEVER blindly reversed: only the (rare) run whose direction fontkit would
//     get wrong is pre-arranged, verified against fontkit itself;
//   * an Arabic paragraph is right-aligned, a Latin one keeps the left margin.
// - Whatever neither face can draw (emoji, other scripts) degrades EXPLICITLY,
//   never silently: the run becomes UNSUPPORTED_MARKER and the report carries a
//   notice pointing to the lossless CSV export. It NEVER applies to Arabic.
// - Not done (documented limitation): GPOS mark positioning (pdf-lib ignores
//   glyph offsets, so diacritics such as harakat sit at their default position),
//   a bold Arabic face (regular is used), color emoji.

const PAGE_WIDTH = 595.28; // A4 at 72dpi
const PAGE_HEIGHT = 841.89;
const MARGIN = 50;
const TITLE_COLOR = rgb(0.18, 0.14, 0.35); // matches AWA's textPrimary family
const TEXT_COLOR = rgb(0.1, 0.1, 0.12);
const MUTED_COLOR = rgb(0.45, 0.43, 0.57);
const RULE_COLOR = rgb(0.85, 0.82, 0.92);

type PdfCharSupport = ReadonlySet<number>;

/** Arabic, Arabic Supplement, Arabic Extended-A, Presentation Forms A and B. */
const ARABIC_SCRIPT_RE = /[؀-ۿݐ-ݿࢠ-ࣿﭐ-﷿ﹰ-﻿]/;

export const containsArabicScript = (text: string): boolean => ARABIC_SCRIPT_RE.test(text);

type FontkitFont = {
  layout: (text: string) => {direction?: string; glyphs: unknown[]};
};

type Fonts = {
  latin: PDFFont;
  latinBold: PDFFont;
  /** null when the report contains no Arabic (the font is then never loaded). */
  arabic: PDFFont | null;
  arabicSupport: PdfCharSupport;
  /** fontkit instance of the same face, used only to ask which direction it
   * will lay a string out in (see arrangeForArabicFace). */
  probe: FontkitFont | null;
};

type Cursor = {doc: PDFDocument; page: PDFPage; y: number; fonts: Fonts; support: PdfCharSupport};

export const PDF_UNSUPPORTED_MARKER = '[…]';
export const PDF_UNSUPPORTED_NOTICE =
  'Remarque : certains caractères (émojis, autres écritures…) ne peuvent pas être affichés dans ce PDF et sont remplacés par « […] ». Ils sont conservés tels quels dans l’export CSV.';

function pdfCharSupport(font: PDFFont): Set<number> {
  return new Set(font.getCharacterSet());
}

/** Zero-width and bidi formatting controls (ZWSP, ZWNJ, ZWJ, LRM, RLM, embedding /
 * isolate controls, BOM). They have no glyph in the embedded face and carry no
 * visible content, so they are dropped before drawing (documented limitation:
 * a ZWNJ no longer prevents two letters from joining). CSV keeps them. */
const INVISIBLE_CONTROLS_RE = /[​-‏‪-‮⁦-⁩﻿]/g;

/** Replaces every maximal run of characters neither PDF face can encode by
 * PDF_UNSUPPORTED_MARKER. Everything drawable is kept verbatim (accents, « »,
 * ’, €, Arabic when its face is loaded…). Pure and deterministic; never throws. */
export function sanitizeTextForPdf(text: string, support: PdfCharSupport): {text: string; replaced: boolean} {
  let out = '';
  let replaced = false;
  let inRun = false;
  for (const char of text.normalize('NFC').replace(INVISIBLE_CONTROLS_RE, '')) {
    const codePoint = char.codePointAt(0) as number;
    if (support.has(codePoint)) {
      out += char;
      inRun = false;
    } else {
      if (!inRun) {out += PDF_UNSUPPORTED_MARKER;}
      inRun = true;
      replaced = true;
    }
  }
  return {text: out, replaced};
}

function collectModelStrings(model: ExportReportModel): string[] {
  const strings = [model.objectiveLabel, model.periodLabel, model.generatedAtLabel, ...model.notices];
  model.categoryCounts.forEach(({label}) => strings.push(label));
  model.days.forEach(day => {
    strings.push(day.dateLabel);
    day.categories.forEach(category => {
      strings.push(category.label);
      strings.push(...category.lines);
    });
  });
  return strings;
}

/* ------------------------------------------------------------------ *
 * Bidirectional layout of one line
 * ------------------------------------------------------------------ */

const bidi = bidiFactory();

const reverseChars = (text: string): string => text.split('').reverse().join('');

/** Base direction of a paragraph: the first strong character decides (UAX #9
 * P2/P3). 1 = right-to-left. */
function paragraphLevel(text: string): 0 | 1 {
  const {paragraphs} = bidi.getEmbeddingLevels(text);
  return paragraphs[0]?.level === 1 ? 1 : 0;
}

/** A string whose glyphs, once fontkit has laid it out (joining forms applied,
 * glyph order reversed for right-to-left text), read in the requested visual
 * direction. fontkit picks the direction from the script of the string itself:
 * for the normal case — Arabic letters drawn right-to-left — the logical string
 * is already right. It is only pre-arranged when the verified outcome differs
 * (e.g. Arabic-Indic digits, which are numbers: left-to-right inside Arabic
 * text). Both candidates are checked against fontkit; nothing is guessed. */
export function arrangeForArabicFace(
  text: string,
  wantRtl: boolean,
  probe: FontkitFont,
): string {
  const visual = wantRtl ? reverseChars(text) : text;
  const outcome = (candidate: string): string =>
    probe.layout(candidate).direction === 'rtl' ? reverseChars(candidate) : candidate;
  if (outcome(text) === visual) {return text;}
  const reversed = reverseChars(text);
  if (outcome(reversed) === visual) {return reversed;}
  return visual;
}

type DrawRun = {text: string; font: PDFFont};

/** The runs of one (already wrapped) line, in VISUAL left-to-right order, each
 * with the exact string to hand to pdf-lib and the face to draw it with. */
export function layoutLineRuns(line: string, paraLevel: 0 | 1, fonts: Fonts, bold: boolean): DrawRun[] {
  const latinFont = bold ? fonts.latinBold : fonts.latin;
  if (!fonts.arabic || !fonts.probe || !containsArabicScript(line)) {
    // No Arabic on this line: plain left-to-right text, exactly as before.
    return line ? [{text: line, font: latinFont}] : [];
  }
  const arabic = fonts.arabic;
  const probe = fonts.probe;
  const {levels} = bidi.getEmbeddingLevels(line, paraLevel === 1 ? 'rtl' : 'ltr');
  const chars = line.split('');

  // 1. Runs of equal embedding level, logical order.
  type LevelRun = {chars: string[]; level: number};
  const levelRuns: LevelRun[] = [];
  chars.forEach((ch, index) => {
    const level = levels[index];
    const last = levelRuns[levelRuns.length - 1];
    if (last && last.level === level) {last.chars.push(ch);} else {levelRuns.push({chars: [ch], level});}
  });

  // 2. Visual order of the runs (UAX #9 rule L2).
  const maxLevel = Math.max(...levelRuns.map(run => run.level));
  const oddLevels = levelRuns.map(run => run.level).filter(level => level % 2 === 1);
  const minOdd = oddLevels.length ? Math.min(...oddLevels) : Infinity;
  const ordered = [...levelRuns];
  for (let level = maxLevel; level >= minOdd; level -= 1) {
    let start = -1;
    for (let index = 0; index <= ordered.length; index += 1) {
      const inScope = index < ordered.length && ordered[index].level >= level;
      if (inScope && start < 0) {start = index;}
      if (!inScope && start >= 0) {
        const reversed = ordered.slice(start, index).reverse();
        ordered.splice(start, index - start, ...reversed);
        start = -1;
      }
    }
  }

  // 3. Each run -> drawable pieces. A piece is drawn with the Arabic face when it
  // is Arabic script (or, inside a right-to-left run, a neutral the Arabic face
  // has); otherwise with Helvetica.
  const pieces: DrawRun[] = [];
  ordered.forEach(run => {
    const rtl = run.level % 2 === 1;
    const source = rtl ? run.chars.map(ch => bidi.getMirroredCharacter(ch) ?? ch) : run.chars;
    type Piece = {chars: string[]; arabic: boolean};
    const logical: Piece[] = [];
    source.forEach(ch => {
      const cp = ch.codePointAt(0) as number;
      // Inside a right-to-left run only Arabic letters and neutrals remain
      // (Latin letters and digits are left-to-right runs of their own).
      // (The list bullet keeps Helvetica's glyph even at the start of an Arabic line.)
      const useArabic = ARABIC_SCRIPT_RE.test(ch) || (rtl && ch !== '•' && fonts.arabicSupport.has(cp));
      const last = logical[logical.length - 1];
      if (last && last.arabic === useArabic) {last.chars.push(ch);} else {logical.push({chars: [ch], arabic: useArabic});}
    });
    const visualPieces = rtl ? [...logical].reverse() : logical;
    visualPieces.forEach(piece => {
      const text = piece.chars.join('');
      if (piece.arabic) {
        pieces.push({text: arrangeForArabicFace(text, rtl, probe), font: arabic});
      } else {
        // Helvetica draws strictly left to right: an RTL run of neutrals is reversed.
        pieces.push({text: rtl ? reverseChars(text) : text, font: latinFont});
      }
    });
  });
  return pieces.filter(piece => piece.text.length > 0);
}

const runsWidth = (runs: DrawRun[], size: number): number =>
  runs.reduce((sum, run) => sum + run.font.widthOfTextAtSize(run.text, size), 0);

function wrapText(
  fonts: Fonts,
  text: string,
  size: number,
  bold: boolean,
  maxWidth: number,
  paraLevel: 0 | 1,
): string[] {
  const measure = (candidate: string): number =>
    runsWidth(layoutLineRuns(candidate, paraLevel, fonts, bold), size);
  const words = text.split(/\s+/).filter(Boolean);
  const lines: string[] = [];
  let current = '';
  words.forEach(word => {
    const candidate = current ? `${current} ${word}` : word;
    if (measure(candidate) > maxWidth && current) {
      lines.push(current);
      current = word;
    } else {
      current = candidate;
    }
  });
  if (current) {lines.push(current);}
  return lines.length ? lines : [''];
}

function newPage(doc: PDFDocument): PDFPage {
  return doc.addPage([PAGE_WIDTH, PAGE_HEIGHT]);
}

function ensureSpace(cursor: Cursor, needed: number): void {
  if (cursor.y - needed < MARGIN) {
    cursor.page = newPage(cursor.doc);
    cursor.y = PAGE_HEIGHT - MARGIN;
  }
}

function drawParagraph(
  cursor: Cursor,
  text: string,
  opts: {size: number; bold?: boolean; color?: ReturnType<typeof rgb>; gapAfter?: number; indent?: number},
): void {
  const {fonts} = cursor;
  const indent = opts.indent ?? 0;
  const maxWidth = PAGE_WIDTH - MARGIN * 2 - indent;
  const clean = sanitizeTextForPdf(text, cursor.support).text;
  const hasArabic = Boolean(fonts.arabic) && containsArabicScript(clean);
  const paraLevel: 0 | 1 = hasArabic ? paragraphLevel(clean) : 0;
  const lines = wrapText(fonts, clean, opts.size, Boolean(opts.bold), maxWidth, paraLevel);
  lines.forEach(line => {
    ensureSpace(cursor, opts.size * 1.4);
    const runs = layoutLineRuns(line, paraLevel, fonts, Boolean(opts.bold));
    const width = runsWidth(runs, opts.size);
    // A right-to-left paragraph is right-aligned (its indent is taken from the
    // right margin); a left-to-right one keeps the left margin, as before.
    let x = paraLevel === 1 ? PAGE_WIDTH - MARGIN - indent - width : MARGIN + indent;
    runs.forEach(run => {
      cursor.page.drawText(run.text, {
        x,
        y: cursor.y,
        size: opts.size,
        font: run.font,
        color: opts.color ?? TEXT_COLOR,
      });
      x += run.font.widthOfTextAtSize(run.text, opts.size);
    });
    cursor.y -= opts.size * 1.4;
  });
  if (opts.gapAfter) {cursor.y -= opts.gapAfter;}
}

function drawRule(cursor: Cursor): void {
  ensureSpace(cursor, 14);
  cursor.page.drawLine({
    start: {x: MARGIN, y: cursor.y},
    end: {x: PAGE_WIDTH - MARGIN, y: cursor.y},
    thickness: 0.75,
    color: RULE_COLOR,
  });
  cursor.y -= 14;
}

/** Renders the full report as a real PDF file's bytes (base64-encoded, ready
 * to be written to disk with @dr.pogodin/react-native-fs's `writeFile(path,
 * base64, 'base64')` — no separate binary/Uint8Array conversion needed).
 * Every line comes straight from the already-filtered, already-selected-only
 * `model` — this function never re-derives, filters, or invents content. */
export async function generateMedicalExportPdfBase64(model: ExportReportModel): Promise<string> {
  const doc = await PDFDocument.create();
  const latin = await doc.embedFont(StandardFonts.Helvetica);
  const latinBold = await doc.embedFont(StandardFonts.HelveticaBold);

  // The Arabic face is only loaded (and embedded) when the report contains Arabic.
  const strings = collectModelStrings(model);
  const needsArabic = strings.some(containsArabicScript);
  let arabic: PDFFont | null = null;
  let probe: FontkitFont | null = null;
  if (needsArabic) {
    doc.registerFontkit(fontkit);
    arabic = await doc.embedFont(CAIRO_ARABIC_SUBSET_BASE64, {subset: true});
    probe = fontkit.create(decodeFromBase64(CAIRO_ARABIC_SUBSET_BASE64)) as unknown as FontkitFont;
  }
  const arabicSupport: PdfCharSupport = arabic ? pdfCharSupport(arabic) : new Set<number>();
  const fonts: Fonts = {latin, latinBold, arabic, arabicSupport, probe};
  // Bold shares the regular face's WinAnsi character set, so one check covers both.
  const support: PdfCharSupport = new Set<number>([...pdfCharSupport(latin), ...arabicSupport]);
  const cursor: Cursor = {doc, page: newPage(doc), y: PAGE_HEIGHT - MARGIN, fonts, support};

  drawParagraph(cursor, 'AWA', {size: 22, bold: true, color: TITLE_COLOR, gapAfter: 2});
  drawParagraph(cursor, 'Rapport de suivi', {size: 15, bold: true, color: TITLE_COLOR, gapAfter: 10});
  drawParagraph(cursor, `Objectif : ${model.objectiveLabel}`, {size: 10.5, color: MUTED_COLOR});
  drawParagraph(cursor, `Période : ${model.periodLabel}`, {size: 10.5, color: MUTED_COLOR});
  drawParagraph(cursor, `Généré le ${model.generatedAtLabel}`, {size: 10.5, color: MUTED_COLOR, gapAfter: 12});

  const hasUnsupportedText = strings.some(value => sanitizeTextForPdf(value, support).replaced);
  const notices = hasUnsupportedText ? [...model.notices, PDF_UNSUPPORTED_NOTICE] : model.notices;

  if (notices.length) {
    notices.forEach(notice => {
      drawParagraph(cursor, notice, {size: 9.5, color: MUTED_COLOR, gapAfter: 2});
    });
    cursor.y -= 4;
  }

  drawRule(cursor);
  cursor.y -= 6;

  drawParagraph(cursor, 'RÉSUMÉ', {size: 12.5, bold: true, color: TITLE_COLOR, gapAfter: 6});
  drawParagraph(cursor, `Nombre de jours renseignés : ${model.totalDays}`, {size: 10.5, gapAfter: 4});
  if (model.categoryCounts.length) {
    model.categoryCounts.forEach(({label, count}) => {
      drawParagraph(cursor, `${label} : ${count} jour${count > 1 ? 's' : ''}`, {size: 10.5, indent: 8});
    });
  }
  cursor.y -= 8;
  drawRule(cursor);
  cursor.y -= 6;

  drawParagraph(cursor, 'HISTORIQUE', {size: 12.5, bold: true, color: TITLE_COLOR, gapAfter: 6});

  if (!model.days.length) {
    drawParagraph(cursor, 'Aucune donnée disponible pour cette période et ces catégories.', {
      size: 10.5,
      color: MUTED_COLOR,
    });
  }

  model.days.forEach(day => {
    ensureSpace(cursor, 24);
    drawParagraph(cursor, day.dateLabel, {size: 11.5, bold: true, gapAfter: 3});
    day.categories.forEach(category => {
      drawParagraph(cursor, category.label, {size: 10, bold: true, indent: 8, gapAfter: 1});
      category.lines.forEach(line => {
        drawParagraph(cursor, `• ${line}`, {size: 10, indent: 16});
      });
      cursor.y -= 2;
    });
    cursor.y -= 6;
  });

  return doc.saveAsBase64();
}
