import React,{useEffect,useState} from 'react';
import {Pressable,ScrollView,Share,StatusBar,StyleSheet,Text,TextInput,View} from 'react-native';
import AsyncStorage from '@react-native-async-storage/async-storage';
import {MaterialDesignIcons} from '@react-native-vector-icons/material-design-icons';
import type {NativeStackScreenProps} from '@react-navigation/native-stack';
import {SafeAreaView,useSafeAreaInsets} from 'react-native-safe-area-context';
import type {RootStackParamList} from '../navigation/AppNavigator';
const PURPLE='#6D4AE8',DARK='#2F2258',MUTED='#746D92';
function Shell({title,navigation,children}:{title:string;navigation:{goBack:()=>void};children:React.ReactNode}){const insets=useSafeAreaInsets();return <SafeAreaView edges={['left','right']} style={s.safe}><StatusBar translucent backgroundColor="transparent" barStyle="dark-content"/><View style={[s.header,{paddingTop:Math.max(insets.top,18)+8}]}><Pressable onPress={navigation.goBack} style={s.back}><MaterialDesignIcons color={PURPLE} name="chevron-left" size={28}/></Pressable><Text style={s.title}>{title}</Text><View style={s.spacer}/></View><ScrollView contentContainerStyle={[s.content,{paddingBottom:Math.max(insets.bottom,18)+24}]}>{children}</ScrollView></SafeAreaView>}
async function readAwaData(){const keys=(await AsyncStorage.getAllKeys()).filter(key=>key.startsWith('@awa')||key.startsWith('@hawa'));const pairs=await Promise.all(keys.map(async key=>[key,await AsyncStorage.getItem(key)] as const));return Object.fromEntries(pairs)}
export function DataManagementScreen({navigation}:NativeStackScreenProps<RootStackParamList,'DataManagement'>){const [count,setCount]=useState(0);const [message,setMessage]=useState('');useEffect(()=>{readAwaData().then(data=>setCount(Object.keys(data).length))},[]);const exportData=async()=>{const data=await readAwaData();await Share.share({title:'Mes données AWA',message:JSON.stringify(data,null,2)})};return <Shell navigation={navigation} title="Gestion des données"><View style={s.hero}><MaterialDesignIcons color={PURPLE} name="database-lock-outline" size={35}/><Text style={s.heroTitle}>Tes données AWA</Text><Text style={s.text}>{count} espaces de stockage locaux sont actuellement utilisés sur cet appareil.</Text></View><Pressable onPress={exportData} style={s.action}><MaterialDesignIcons color={PURPLE} name="export-variant" size={22}/><View style={s.actionCopy}><Text style={s.actionTitle}>Exporter mes données</Text><Text style={s.text}>Créer une copie JSON via le menu de partage sécurisé.</Text></View></Pressable><Pressable onPress={()=>setMessage('Pour tout supprimer, utilise « Supprimer mon compte » dans l’écran précédent.')} style={s.secondary}><Text style={s.secondaryText}>Informations sur la suppression</Text></Pressable>{message?<Text style={s.notice}>{message}</Text>:null}</Shell>}
export function DeleteAccountScreen({navigation}:NativeStackScreenProps<RootStackParamList,'DeleteAccount'>){const [value,setValue]=useState('');const [error,setError]=useState('');const remove=async()=>{if(value.trim().toUpperCase()!=='SUPPRIMER'){setError('Écris SUPPRIMER pour confirmer.');return;}await AsyncStorage.clear();navigation.reset({index:0,routes:[{name:'Welcome'}]})};return <Shell navigation={navigation} title="Supprimer mon compte"><View style={s.warning}><MaterialDesignIcons color="#D94458" name="alert-outline" size={35}/><Text style={s.warningTitle}>Cette action est irréversible</Text><Text style={s.text}>Toutes les données AWA enregistrées localement sur cet appareil seront définitivement supprimées.</Text></View><Text style={s.label}>Écris SUPPRIMER pour confirmer</Text><TextInput autoCapitalize="characters" onChangeText={text=>{setValue(text);setError('')}} style={[s.input,error&&s.inputError]} value={value}/>{error?<Text style={s.error}>{error}</Text>:null}<Pressable onPress={remove} style={s.delete}><Text style={s.deleteText}>Supprimer définitivement</Text></Pressable></Shell>}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:'#FCFAFF'},header:{flexDirection:'row',alignItems:'center',paddingHorizontal:16,paddingBottom:12},back:{alignItems:'center',justifyContent:'center',borderRadius:999,backgroundColor:'#FFF',padding:9,elevation:2},title:{flex:1,color:DARK,fontFamily:'serif',fontSize:20,fontWeight:'700',textAlign:'center'},spacer:{padding:23},content:{paddingHorizontal:16,gap:13},hero:{alignItems:'center',borderWidth:1,borderColor:'#EEE7F5',borderRadius:24,backgroundColor:'#FFF',padding:20},heroTitle:{marginTop:9,color:DARK,fontFamily:'serif',fontSize:18,fontWeight:'700'},text:{marginTop:6,color:MUTED,fontSize:12,lineHeight:18,textAlign:'center'},action:{flexDirection:'row',alignItems:'center',borderWidth:1,borderColor:'#E7DDF4',borderRadius:20,backgroundColor:'#FFF',padding:15},actionCopy:{flex:1,marginLeft:12},actionTitle:{color:DARK,fontSize:13.5,fontWeight:'700'},secondary:{alignItems:'center',borderRadius:18,backgroundColor:'#F1E8FF',padding:14},secondaryText:{color:PURPLE,fontSize:12,fontWeight:'700'},notice:{color:MUTED,fontSize:11.5,lineHeight:17,textAlign:'center'},warning:{alignItems:'center',borderWidth:1,borderColor:'#F2CDD3',borderRadius:24,backgroundColor:'#FFF8F9',padding:20},warningTitle:{marginTop:9,color:'#D94458',fontFamily:'serif',fontSize:18,fontWeight:'700'},label:{marginTop:4,color:DARK,fontSize:12,fontWeight:'700'},input:{borderWidth:1,borderColor:'#DDD2ED',borderRadius:18,backgroundColor:'#FFF',padding:13,color:DARK,fontSize:14},inputError:{borderColor:'#D94458'},error:{color:'#D94458',fontSize:11},delete:{alignItems:'center',borderRadius:18,backgroundColor:'#D94458',padding:15},deleteText:{color:'#FFF',fontSize:14,fontWeight:'700'}});
