import React,{useCallback,useEffect,useState} from 'react';
import {Pressable,ScrollView,StatusBar,StyleSheet,Switch,Text,useWindowDimensions,View} from 'react-native';
import {MaterialDesignIcons} from '@react-native-vector-icons/material-design-icons';
import {useFocusEffect} from '@react-navigation/native';
import type {NativeStackScreenProps} from '@react-navigation/native-stack';
import Animated,{FadeIn,FadeInUp} from 'react-native-reanimated';
import {SafeAreaView,useSafeAreaInsets} from 'react-native-safe-area-context';
import type {RootStackParamList} from '../navigation/AppNavigator';
import {getPrivacySecuritySettings,isBiometricEnabled,isPinEnabled,loadSecurityPreferences,updatePrivacySecuritySettings,type PrivacySecuritySettings} from '../state/securityPreferences';
import {getAvailableBiometry} from '../services/appSecurityService';
const PURPLE='#6D4AE8',DARK='#2F2258',MUTED='#746D92';
type Props=NativeStackScreenProps<RootStackParamList,'PrivacySecurity'>;type IconName=React.ComponentProps<typeof MaterialDesignIcons>['name'];

function SettingRow({icon,title,subtitle,status,onPress,last,danger,toggle,onToggle}:{icon:IconName;title:string;subtitle:string;status?:string;onPress?:()=>void;last?:boolean;danger?:boolean;toggle?:boolean;onToggle?:(value:boolean)=>void}){return <Pressable accessibilityLabel={title} disabled={!onPress&&!onToggle} onPress={onPress} style={({pressed})=>[styles.row,!last&&styles.rowBorder,pressed&&styles.pressed]}><View style={[styles.rowIcon,danger&&styles.dangerIcon]}><MaterialDesignIcons color={danger?'#E04F62':PURPLE} name={icon} size={19}/></View><View style={styles.rowCopy}><Text style={[styles.rowTitle,danger&&styles.dangerText]}>{title}</Text><Text style={styles.rowSubtitle}>{subtitle}</Text></View>{onToggle?<Switch ios_backgroundColor="#D9CDEC" onValueChange={onToggle} thumbColor="#FFF" trackColor={{false:'#D9CDEC',true:PURPLE}} value={Boolean(toggle)}/>:<>{status?<Text style={styles.status}>{status}</Text>:null}{onPress?<MaterialDesignIcons color="#B5ACC5" name="chevron-right" size={22}/>:null}</>}</Pressable>}

export default function PrivacySecurityScreen({navigation}:Props):React.JSX.Element{const insets=useSafeAreaInsets();const {width,height}=useWindowDimensions();const compact=width<360||height<700;const [settings,setSettings]=useState(getPrivacySecuritySettings());const [pin,setPin]=useState(isPinEnabled());const [bio,setBio]=useState(isBiometricEnabled());const[biometryLabel,setBiometryLabel]=useState('Biométrie');
  useEffect(()=>{loadSecurityPreferences().then(()=>{setSettings(getPrivacySecuritySettings());setPin(isPinEnabled());setBio(isBiometricEnabled())});getAvailableBiometry().then(value=>{if(value){setBiometryLabel(value.label);}}).catch(()=>{});},[]);
  useFocusEffect(useCallback(()=>{setPin(isPinEnabled());setBio(isBiometricEnabled());setSettings(getPrivacySecuritySettings())},[]));
  const change=<K extends keyof PrivacySecuritySettings>(key:K,value:PrivacySecuritySettings[K])=>setSettings(updatePrivacySecuritySettings({[key]:value}));
  return <SafeAreaView edges={['left','right']} style={styles.safe}><StatusBar translucent backgroundColor="transparent" barStyle="dark-content"/><ScrollView contentContainerStyle={[styles.content,compact&&styles.contentCompact,{paddingTop:Math.max(insets.top,18)+8,paddingBottom:Math.max(insets.bottom,18)+25}]} showsVerticalScrollIndicator={false}>
    <Animated.View entering={FadeIn.duration(300)} style={styles.header}><Pressable accessibilityLabel="Retour" onPress={navigation.goBack} style={({pressed})=>[styles.back,pressed&&styles.pressed]}><MaterialDesignIcons color={PURPLE} name="chevron-left" size={28}/></Pressable><View style={styles.headerCopy}><Text adjustsFontSizeToFit minimumFontScale={.78} style={styles.title}>Confidentialité & Sécurité</Text><Text style={styles.subtitle}>Tes données, ta vie privée, ton choix 💜</Text></View><View style={styles.decor}><MaterialDesignIcons color={PURPLE} name="shield-lock-outline" size={39}/><MaterialDesignIcons color="#B998F0" name="leaf" size={34}/></View></Animated.View>
    <Animated.View entering={FadeInUp.delay(70).duration(420)} style={styles.intro}><View style={styles.introIcon}><MaterialDesignIcons color={PURPLE} name="shield-account-outline" size={28}/></View><View style={styles.introCopy}><Text style={styles.introTitle}>Tu es aux commandes 🔒</Text><Text style={styles.introText}>Gère la confidentialité de tes données et choisis les protections qui te conviennent.</Text></View></Animated.View>
    <Text style={styles.sectionTitle}>Accès et protection</Text><Animated.View entering={FadeInUp.delay(130).duration(420)} style={styles.card}><SettingRow icon="lock-outline" title="Code PIN" subtitle={pin?'Appuie pour modifier ou désactiver':'Protéger l’accès à ton application'} status={pin?'Activé':'Inactif'} onPress={()=>navigation.navigate('PinManagement')}/><SettingRow icon="fingerprint" title={biometryLabel} subtitle={bio?'Appuie pour tester ou désactiver':'Déverrouillage natif sécurisé'} status={bio?'Activée':'Inactive'} onPress={()=>navigation.navigate('FaceIdSetup',{action:bio?'manage':'enable'})}/><SettingRow icon="eye-off-outline" title="Mode discret / pudeur" subtitle="Masquer le contenu sensible de l’application" toggle={settings.discreetMode} onToggle={value=>change('discreetMode',value)}/><SettingRow icon="bell-outline" title="Notifications discrètes" subtitle="Utiliser des notifications discrètes" toggle={settings.discreetNotifications} onToggle={value=>change('discreetNotifications',value)}/><SettingRow icon="cellphone-lock" title="Masquer l’aperçu des notifications" subtitle="Ne pas afficher le contenu sur l’écran verrouillé" toggle={settings.hideNotificationPreview} onToggle={value=>change('hideNotificationPreview',value)}/><SettingRow last icon="shape-outline" title="Apparence discrète" subtitle="Nom et icône de l’application sur l’écran d’accueil" onPress={()=>navigation.navigate('DiscreetLauncher')}/></Animated.View>
    <Text style={styles.sectionTitle}>Contenu sensible</Text><Animated.View entering={FadeInUp.delay(190).duration(420)} style={styles.card}><SettingRow icon="heart-outline" title="Protection de Vie intime" subtitle="Verrouiller la section Vie intime" status={settings.intimacyProtection?'Activée':'Inactive'} onPress={()=>change('intimacyProtection',!settings.intimacyProtection)}/><SettingRow last icon="image-lock-outline" title="Protection des Notes / Photos privées" subtitle="Verrouiller tes notes et photos personnelles" status={settings.privateContentProtection?'Activée':'Inactive'} onPress={()=>change('privateContentProtection',!settings.privateContentProtection)}/></Animated.View>
    <Text style={styles.sectionTitle}>Compte et données</Text><Animated.View entering={FadeInUp.delay(250).duration(420)} style={styles.card}><SettingRow icon="account-outline" title="Mode anonyme" subtitle="Utiliser l’application sans partager ton identité" status={settings.anonymousMode?'Activé':'Inactif'} onPress={()=>navigation.navigate('AnonymousMode')}/><SettingRow icon="cloud-outline" title="Gestion des données" subtitle="Voir, exporter ou supprimer tes données" onPress={()=>navigation.navigate('DataManagement')}/><SettingRow danger last icon="delete-outline" title="Supprimer mon compte" subtitle="Supprimer définitivement ton compte et tes données" onPress={()=>navigation.navigate('DeleteAccount')}/></Animated.View>
    <View style={styles.info}><MaterialDesignIcons color={PURPLE} name="information-outline" size={21}/><Text style={styles.infoText}>Tes paramètres de confidentialité restent sous ton contrôle.{`\n`}Tu peux les modifier à tout moment.</Text></View>
  </ScrollView></SafeAreaView>}
const styles=StyleSheet.create({safe:{flex:1,backgroundColor:'#FCFAFF'},content:{flexGrow:1,gap:12,paddingHorizontal:16},contentCompact:{paddingHorizontal:11},header:{flexDirection:'row',alignItems:'center'},back:{alignItems:'center',justifyContent:'center',borderRadius:999,backgroundColor:'#FFF',padding:9,elevation:2},headerCopy:{flex:1,minWidth:0,paddingHorizontal:9},title:{color:DARK,fontFamily:'serif',fontSize:23,fontWeight:'700'},subtitle:{marginTop:4,color:MUTED,fontSize:12.5,lineHeight:17},decor:{flexDirection:'row',alignItems:'center'},intro:{flexDirection:'row',alignItems:'center',borderWidth:1,borderColor:'#E8DDF5',borderRadius:24,backgroundColor:'#FAF7FF',padding:15},introIcon:{alignItems:'center',justifyContent:'center',borderRadius:999,backgroundColor:'#EEE4FF',padding:13},introCopy:{flex:1,marginLeft:12},introTitle:{color:DARK,fontSize:15,fontWeight:'700'},introText:{marginTop:5,color:MUTED,fontSize:12,lineHeight:17},sectionTitle:{color:DARK,fontFamily:'serif',fontSize:16,fontWeight:'700'},card:{overflow:'hidden',borderWidth:1,borderColor:'#EEE7F5',borderRadius:24,backgroundColor:'#FFF',paddingHorizontal:11},row:{minHeight:70,flexDirection:'row',alignItems:'center',paddingVertical:10},rowBorder:{borderBottomWidth:StyleSheet.hairlineWidth,borderBottomColor:'#EEE8F3'},rowIcon:{alignItems:'center',justifyContent:'center',borderRadius:13,backgroundColor:'#F2EBFF',padding:9},dangerIcon:{backgroundColor:'#FFE9EC'},rowCopy:{flex:1,minWidth:0,marginHorizontal:10},rowTitle:{color:DARK,fontSize:13.5,fontWeight:'700'},dangerText:{color:'#D94458'},rowSubtitle:{marginTop:4,color:MUTED,fontSize:11.5,lineHeight:16},status:{color:PURPLE,fontSize:11,fontWeight:'600',marginRight:3},info:{flexDirection:'row',alignItems:'center',gap:10,borderRadius:18,backgroundColor:'#F1E8FF',padding:14},infoText:{flex:1,color:MUTED,fontSize:11.5,lineHeight:17},pressed:{opacity:.78,transform:[{scale:.985}]}});
