import React, {useMemo} from 'react';
import {Pressable,ScrollView,StatusBar,StyleSheet,Text,View} from 'react-native';
import {MaterialDesignIcons} from '@react-native-vector-icons/material-design-icons';
import type {NativeStackScreenProps} from '@react-navigation/native-stack';
import {SafeAreaView,useSafeAreaInsets} from 'react-native-safe-area-context';
import type {RootStackParamList} from '../navigation/AppNavigator';
import {APP_METADATA} from '../utils/appMetadata';
import {FAQ_ITEMS,GUIDE_ITEMS} from '../utils/supportContent';
import {useAwaTheme} from '../theme/AwaThemeProvider';
import {type ResolvedAwaTheme} from '../theme/awaThemeTokens';

function Shell({title,navigation,children,theme,styles}:{title:string;navigation:{goBack:()=>void};children:React.ReactNode;theme:ResolvedAwaTheme;styles:ReturnType<typeof createStyles>}){const insets=useSafeAreaInsets();return <SafeAreaView edges={['left','right']} style={styles.safe}><StatusBar translucent backgroundColor="transparent" barStyle={theme.statusBarStyle}/><View style={[styles.header,{paddingTop:Math.max(insets.top,18)+8}]}><Pressable accessibilityLabel="Retour" onPress={navigation.goBack} style={styles.back}><MaterialDesignIcons color={theme.colors.primary} name="chevron-left" size={28}/></Pressable><Text style={styles.title}>{title}</Text><View style={styles.spacer}/></View><ScrollView contentContainerStyle={[styles.content,{paddingBottom:Math.max(insets.bottom,18)+24}]}>{children}</ScrollView></SafeAreaView>}
export function FAQScreen({navigation}:NativeStackScreenProps<RootStackParamList,'FAQ'>){const {theme}=useAwaTheme();const styles=useMemo(()=>createStyles(theme),[theme]);return <Shell navigation={navigation} styles={styles} theme={theme} title="Questions fréquentes"><Text style={styles.intro}>Retrouve les réponses essentielles pour utiliser AWA sereinement.</Text>{FAQ_ITEMS.map(item=><Pressable key={item.id} onPress={()=>navigation.navigate('FAQDetail',{id:item.id})} style={({pressed})=>[styles.card,styles.row,pressed&&styles.pressed]}><View style={styles.icon}><MaterialDesignIcons color={theme.colors.primary} name={item.icon as never} size={21}/></View><View style={styles.copy}><Text style={styles.cardTitle}>{item.question}</Text><Text style={styles.text}>{item.subtitle}</Text></View><MaterialDesignIcons color={theme.colors.textMuted} name="chevron-right" size={22}/></Pressable>)}</Shell>}
export function FAQDetailScreen({navigation,route}:NativeStackScreenProps<RootStackParamList,'FAQDetail'>){const {theme}=useAwaTheme();const styles=useMemo(()=>createStyles(theme),[theme]);const item=FAQ_ITEMS.find(value=>value.id===route.params.id)??FAQ_ITEMS[0];return <Shell navigation={navigation} styles={styles} theme={theme} title="FAQ"><View style={styles.detail}><View style={styles.detailIcon}><MaterialDesignIcons color={theme.colors.primary} name={item.icon as never} size={30}/></View><Text style={styles.detailTitle}>{item.question}</Text><Text style={styles.category}>{item.category}</Text><Text style={styles.answer}>{item.answer}</Text></View></Shell>}
export function GuidesScreen({navigation}:NativeStackScreenProps<RootStackParamList,'Guides'>){const {theme}=useAwaTheme();const styles=useMemo(()=>createStyles(theme),[theme]);return <Shell navigation={navigation} styles={styles} theme={theme} title="Guides & tutoriels"><Text style={styles.intro}>Des repères simples pour profiter pleinement d’AWA.</Text>{GUIDE_ITEMS.map(item=><View key={item.title} style={[styles.card,styles.row]}><View style={styles.icon}><MaterialDesignIcons color={theme.colors.primary} name={item.icon as never} size={21}/></View><View style={styles.copy}><Text style={styles.cardTitle}>{item.title}</Text><Text style={styles.text}>{item.text}</Text></View></View>)}</Shell>}
export function WhatsNewScreen({navigation}:NativeStackScreenProps<RootStackParamList,'WhatsNew'>){const {theme}=useAwaTheme();const styles=useMemo(()=>createStyles(theme),[theme]);return <Shell navigation={navigation} styles={styles} theme={theme} title="Nouveautés"><View style={styles.detail}><View style={styles.version}><Text style={styles.versionText}>Version {APP_METADATA.version}</Text></View><Text style={styles.detailTitle}>AWA continue d’évoluer</Text><Text style={styles.answer}>Aucune note de version officielle n’est configurée pour le moment. Les prochaines nouveautés apparaîtront ici après leur publication.</Text></View></Shell>}
function createStyles(theme: ResolvedAwaTheme) {
  return StyleSheet.create({safe:{flex:1,backgroundColor:theme.colors.background},header:{flexDirection:'row',alignItems:'center',paddingHorizontal:16,paddingBottom:12},back:{alignItems:'center',justifyContent:'center',borderRadius:999,backgroundColor:theme.colors.surface,padding:9,elevation:2},title:{flex:1,color:theme.colors.accent,fontFamily:'serif',fontSize:21,fontWeight:'700',textAlign:'center'},spacer:{padding:23},content:{paddingHorizontal:16,gap:10},intro:{color:theme.colors.textSecondary,fontSize:13,lineHeight:19,marginBottom:3},card:{borderWidth:1,borderColor:theme.colors.border,borderRadius:20,backgroundColor:theme.colors.surface,padding:13},row:{flexDirection:'row',alignItems:'center'},icon:{alignItems:'center',justifyContent:'center',borderRadius:14,backgroundColor:theme.colors.primarySoft,padding:10},copy:{flex:1,minWidth:0,marginLeft:11},cardTitle:{color:theme.colors.accent,fontSize:13,fontWeight:'700'},text:{marginTop:3,color:theme.colors.textSecondary,fontSize:11,lineHeight:16},pressed:{opacity:.78,transform:[{scale:.985}]},detail:{alignItems:'center',borderWidth:1,borderColor:theme.colors.border,borderRadius:25,backgroundColor:theme.colors.surface,padding:20},detailIcon:{borderRadius:999,backgroundColor:theme.colors.primarySoft,padding:16},detailTitle:{marginTop:14,color:theme.colors.accent,fontFamily:'serif',fontSize:19,fontWeight:'700',textAlign:'center'},category:{marginTop:7,color:theme.colors.primary,fontSize:11,fontWeight:'700'},answer:{marginTop:13,color:theme.colors.textSecondary,fontSize:13,lineHeight:21,textAlign:'center'},version:{borderRadius:14,backgroundColor:theme.colors.primarySoft,paddingHorizontal:12,paddingVertical:7},versionText:{color:theme.colors.primary,fontSize:11,fontWeight:'700'}});
}
