import React from 'react';
import {Pressable,ScrollView,StatusBar,StyleSheet,Text,View} from 'react-native';
import {MaterialDesignIcons} from '@react-native-vector-icons/material-design-icons';
import type {NativeStackScreenProps} from '@react-navigation/native-stack';
import {SafeAreaView,useSafeAreaInsets} from 'react-native-safe-area-context';
import type {RootStackParamList} from '../navigation/AppNavigator';
import {APP_METADATA} from '../utils/appMetadata';
import {FAQ_ITEMS,GUIDE_ITEMS} from '../utils/supportContent';
const PURPLE='#6D4AE8',DARK='#2F2258',MUTED='#746D92';

function Shell({title,navigation,children}:{title:string;navigation:{goBack:()=>void};children:React.ReactNode}){const insets=useSafeAreaInsets();return <SafeAreaView edges={['left','right']} style={s.safe}><StatusBar translucent backgroundColor="transparent" barStyle="dark-content"/><View style={[s.header,{paddingTop:Math.max(insets.top,18)+8}]}><Pressable accessibilityLabel="Retour" onPress={navigation.goBack} style={s.back}><MaterialDesignIcons color={PURPLE} name="chevron-left" size={28}/></Pressable><Text style={s.title}>{title}</Text><View style={s.spacer}/></View><ScrollView contentContainerStyle={[s.content,{paddingBottom:Math.max(insets.bottom,18)+24}]}>{children}</ScrollView></SafeAreaView>}
export function FAQScreen({navigation}:NativeStackScreenProps<RootStackParamList,'FAQ'>){return <Shell navigation={navigation} title="Questions fréquentes"><Text style={s.intro}>Retrouve les réponses essentielles pour utiliser AWA sereinement.</Text>{FAQ_ITEMS.map(item=><Pressable key={item.id} onPress={()=>navigation.navigate('FAQDetail',{id:item.id})} style={({pressed})=>[s.card,s.row,pressed&&s.pressed]}><View style={s.icon}><MaterialDesignIcons color={PURPLE} name={item.icon as never} size={21}/></View><View style={s.copy}><Text style={s.cardTitle}>{item.question}</Text><Text style={s.text}>{item.subtitle}</Text></View><MaterialDesignIcons color="#B5ACC5" name="chevron-right" size={22}/></Pressable>)}</Shell>}
export function FAQDetailScreen({navigation,route}:NativeStackScreenProps<RootStackParamList,'FAQDetail'>){const item=FAQ_ITEMS.find(value=>value.id===route.params.id)??FAQ_ITEMS[0];return <Shell navigation={navigation} title="FAQ"><View style={s.detail}><View style={s.detailIcon}><MaterialDesignIcons color={PURPLE} name={item.icon as never} size={30}/></View><Text style={s.detailTitle}>{item.question}</Text><Text style={s.category}>{item.category}</Text><Text style={s.answer}>{item.answer}</Text></View></Shell>}
export function GuidesScreen({navigation}:NativeStackScreenProps<RootStackParamList,'Guides'>){return <Shell navigation={navigation} title="Guides & tutoriels"><Text style={s.intro}>Des repères simples pour profiter pleinement d’AWA.</Text>{GUIDE_ITEMS.map(item=><View key={item.title} style={[s.card,s.row]}><View style={s.icon}><MaterialDesignIcons color={PURPLE} name={item.icon as never} size={21}/></View><View style={s.copy}><Text style={s.cardTitle}>{item.title}</Text><Text style={s.text}>{item.text}</Text></View></View>)}</Shell>}
export function WhatsNewScreen({navigation}:NativeStackScreenProps<RootStackParamList,'WhatsNew'>){return <Shell navigation={navigation} title="Nouveautés"><View style={s.detail}><View style={s.version}><Text style={s.versionText}>Version {APP_METADATA.version}</Text></View><Text style={s.detailTitle}>AWA continue d’évoluer</Text><Text style={s.answer}>Aucune note de version officielle n’est configurée pour le moment. Les prochaines nouveautés apparaîtront ici après leur publication.</Text></View></Shell>}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:'#FCFAFF'},header:{flexDirection:'row',alignItems:'center',paddingHorizontal:16,paddingBottom:12},back:{alignItems:'center',justifyContent:'center',borderRadius:999,backgroundColor:'#FFF',padding:9,elevation:2},title:{flex:1,color:DARK,fontFamily:'serif',fontSize:21,fontWeight:'700',textAlign:'center'},spacer:{padding:23},content:{paddingHorizontal:16,gap:10},intro:{color:MUTED,fontSize:13,lineHeight:19,marginBottom:3},card:{borderWidth:1,borderColor:'#EEE7F5',borderRadius:20,backgroundColor:'#FFF',padding:13},row:{flexDirection:'row',alignItems:'center'},icon:{alignItems:'center',justifyContent:'center',borderRadius:14,backgroundColor:'#F2EBFF',padding:10},copy:{flex:1,minWidth:0,marginLeft:11},cardTitle:{color:DARK,fontSize:13,fontWeight:'700'},text:{marginTop:3,color:MUTED,fontSize:11,lineHeight:16},pressed:{opacity:.78,transform:[{scale:.985}]},detail:{alignItems:'center',borderWidth:1,borderColor:'#EEE7F5',borderRadius:25,backgroundColor:'#FFF',padding:20},detailIcon:{borderRadius:999,backgroundColor:'#F0E7FF',padding:16},detailTitle:{marginTop:14,color:DARK,fontFamily:'serif',fontSize:19,fontWeight:'700',textAlign:'center'},category:{marginTop:7,color:PURPLE,fontSize:11,fontWeight:'700'},answer:{marginTop:13,color:MUTED,fontSize:13,lineHeight:21,textAlign:'center'},version:{borderRadius:14,backgroundColor:'#F0E7FF',paddingHorizontal:12,paddingVertical:7},versionText:{color:PURPLE,fontSize:11,fontWeight:'700'}});
