import React from 'react';
import {Pressable, StyleSheet, Text, View} from 'react-native';
import {MaterialDesignIcons} from '@react-native-vector-icons/material-design-icons';
import {PIN_LENGTH} from '../../services/appSecurityService';

const KEYS = ['1','2','3','4','5','6','7','8','9','empty','0','delete'] as const;
export function PinKeypad({value,onChange,disabled=false,error}: {value:string; onChange:(value:string)=>void; disabled?:boolean; error?:string}): React.JSX.Element {
  const press = (key: typeof KEYS[number]) => {if (disabled) {return;} if (key === 'delete') {onChange(value.slice(0,-1));} else if (key !== 'empty' && value.length < PIN_LENGTH) {onChange(`${value}${key}`);}};
  return <><View accessibilityLabel={`${value.length} chiffres saisis sur ${PIN_LENGTH}`} style={styles.dots}>{Array.from({length:PIN_LENGTH},(_,i)=><View key={i} style={[styles.dot,i<value.length&&styles.dotFilled]}/>)}</View>{error?<Text accessibilityRole="alert" style={styles.error}>{error}</Text>:<View style={styles.errorSpace}/>}<View style={styles.keypad}>{KEYS.map((key,index)=>key==='empty'?<View key={key} style={styles.key}/>:<Pressable accessibilityRole="button" accessibilityLabel={key==='delete'?'Effacer le dernier chiffre':`Chiffre ${key}`} disabled={disabled} key={`${key}-${index}`} onPress={()=>press(key)} style={({pressed})=>[styles.key,styles.keyActive,pressed&&styles.pressed]}>{key==='delete'?<MaterialDesignIcons name="backspace-outline" size={25} color="#28166F"/>:<Text style={styles.number}>{key}</Text>}</Pressable>)}</View></>;
}
const styles=StyleSheet.create({dots:{flexDirection:'row',gap:21,marginTop:25},dot:{width:15,height:15,borderRadius:8,borderWidth:1.5,borderColor:'#C8B8E4',backgroundColor:'#FFF'},dotFilled:{borderColor:'#6949BE',backgroundColor:'#6949BE'},error:{height:34,paddingTop:10,color:'#C74669',fontSize:13,fontWeight:'600',textAlign:'center'},errorSpace:{height:34},keypad:{width:238,flexDirection:'row',flexWrap:'wrap',justifyContent:'space-between',rowGap:12},key:{width:62,height:62,alignItems:'center',justifyContent:'center',borderRadius:31},keyActive:{borderWidth:1,borderColor:'rgba(105,73,190,.14)',backgroundColor:'rgba(255,255,255,.92)'},number:{color:'#28166F',fontSize:24},pressed:{opacity:.58,transform:[{scale:.94}]}});
