import React, {useEffect, useRef} from 'react';
import {AccessibilityInfo, Animated, Image, type ImageSourcePropType, KeyboardAvoidingView, Platform, Pressable, SafeAreaView, ScrollView, StatusBar, StyleSheet, Text, View} from 'react-native';
import {MaterialDesignIcons} from '@react-native-vector-icons/material-design-icons';
import {useNavigation, type NavigationProp} from '@react-navigation/native';
import {useSafeAreaInsets} from 'react-native-safe-area-context';
import type {RootStackParamList} from '../../navigation/AppNavigator';

type Props = {title: string; icon: string; children: React.ReactNode; onSave?: () => void; saving?: boolean; error?: string; heroSource?: ImageSourcePropType; heroLabel?: string; saveLabel?: string ; heroLabelBesideIcon?: boolean; hideJournalHeader?: boolean; toast?: React.ReactNode;};

export function JournalScreenLayout({title, icon, children, onSave, saving, error, heroSource, heroLabel, saveLabel = 'Enregistrer', hideJournalHeader = false, toast}: Props): React.JSX.Element {
  const navigation = useNavigation<NavigationProp<RootStackParamList>>();
  const insets = useSafeAreaInsets();
  const entrance = useRef(new Animated.Value(0)).current;
  useEffect(() => {AccessibilityInfo.isReduceMotionEnabled().then(reduce => Animated.timing(entrance, {toValue: 1, duration: reduce ? 0 : 280, useNativeDriver: true}).start());}, [entrance]);
  const date = new Intl.DateTimeFormat('fr-FR', {weekday: 'long', day: 'numeric', month: 'long'}).format(new Date());
  return <SafeAreaView style={styles.safe}><StatusBar backgroundColor="#F8F4FC" barStyle="dark-content" /><KeyboardAvoidingView behavior={Platform.OS === 'ios' ? 'padding' : undefined} keyboardVerticalOffset={insets.top} style={styles.flex}><View style={styles.header}><Pressable accessibilityLabel="Retour" accessibilityRole="button" onPress={navigation.goBack} style={styles.back}><MaterialDesignIcons color="#33206F" name="chevron-left" size={28} /></Pressable><View style={styles.headerCopy}>{!hideJournalHeader ? <Text style={styles.eyebrow}>Journal quotidien</Text> : null}<Text style={styles.title}>{title}</Text><Text style={styles.date}>Aujourd’hui · {date}</Text></View><View style={styles.headerIcon}><MaterialDesignIcons color="#6949BE" name="information-outline" size={22} /></View></View><Animated.View style={[styles.flex, {opacity: entrance, transform: [{translateY: entrance.interpolate({inputRange: [0, 1], outputRange: [10, 0]})}]}]}><ScrollView contentContainerStyle={[styles.content, {paddingBottom: Math.max(insets.bottom, 16) + 30}]} keyboardShouldPersistTaps="handled" showsVerticalScrollIndicator={false}>{heroSource ? <View style={styles.hero}><View style={styles.heroCopy}><View style={styles.heroIcon}><MaterialDesignIcons color="#6949BE" name={icon as never} size={21} /></View><Text style={styles.heroLabel}>{heroLabel ?? title}</Text></View><Image resizeMode="contain" source={heroSource} style={styles.heroImage} /></View> : null}{children}{error ? <Text accessibilityRole="alert" style={styles.error}>{error}</Text> : null}{onSave ? <Pressable accessibilityLabel={saveLabel} accessibilityRole="button" disabled={saving} onPress={onSave} style={({pressed}) => [styles.save, pressed && styles.pressed, saving && styles.disabled]}><MaterialDesignIcons color="#FFFFFF" name="check-circle-outline" size={22} /><Text style={styles.saveText}>{saving ? 'Enregistrement…' : saveLabel}</Text></Pressable> : null}<View style={styles.privacy}><MaterialDesignIcons color="#8573B5" name="lock-outline" size={15} /><Text style={styles.privacyText}>Tes données sont privées et sécurisées selon tes réglages.</Text></View></ScrollView></Animated.View></KeyboardAvoidingView>{toast}</SafeAreaView>;
}

export function SectionCard({title, children}: {title: string; children: React.ReactNode}) {return <View style={styles.section}><Text style={styles.sectionTitle}>{title}</Text>{children}</View>;}

export function ChoiceChips({options, value, values, onChange, multiple}: {options: string[]; value?: string; values?: string[]; onChange: (value: string) => void; multiple?: boolean}) {return <View style={styles.chips}>{options.map(option => {const selected = multiple ? values?.includes(option) : value === option; return <Pressable key={option} accessibilityRole={multiple ? 'checkbox' : 'radio'} accessibilityState={{checked: Boolean(selected)}} onPress={() => onChange(option)} style={({pressed}) => [styles.chip, selected && styles.chipSelected, pressed && styles.pressed]}><Text style={[styles.chipText, selected && styles.chipTextSelected]}>{option}</Text></Pressable>;})}</View>;}

const styles = StyleSheet.create({safe: {flex: 1, backgroundColor: '#F8F4FC'}, flex: {flex: 1}, header: {minHeight: 104, flexDirection: 'row', alignItems: 'center', paddingHorizontal: 14, paddingVertical: 8}, back: {width: 44, height: 44, alignItems: 'center', justifyContent: 'center', borderRadius: 16, backgroundColor: '#FFFFFF', borderWidth: 1, borderColor: '#E9E1F2'}, headerCopy: {flex: 1, alignItems: 'center', paddingHorizontal: 6}, eyebrow: {color: '#7253B5', fontSize: 11, fontWeight: '700'}, title: {marginTop: 3, color: '#201151', fontSize: 22, fontWeight: '800', textAlign: 'center'}, date: {marginTop: 4, color: '#6B6281', fontSize: 11}, headerIcon: {width: 42, height: 42, alignItems: 'center', justifyContent: 'center', borderRadius: 16, backgroundColor: '#FFFFFF', borderWidth: 1, borderColor: '#E9E1F2'}, content: {paddingHorizontal: 14, paddingTop: 4, paddingBottom: 30, gap: 12}, hero: {height: 126, flexDirection: 'row', alignItems: 'center', overflow: 'hidden', borderRadius: 24, backgroundColor: '#F0E7F8', borderWidth: 1, borderColor: '#E4D8F0'}, heroCopy: {flex: 1, paddingLeft: 18}, heroIcon: {width: 38, height: 38, alignItems: 'center', justifyContent: 'center', borderRadius: 14, backgroundColor: 'rgba(255,255,255,0.82)'}, heroLabel: {marginTop: 8, color: '#33206F', fontSize: 14, lineHeight: 18, fontWeight: '800'}, heroImage: {width: 132, height: 132, marginRight: -4}, section: {borderWidth: 1, borderColor: '#E8E0EF', borderRadius: 22, backgroundColor: '#FFFEFF', padding: 15, shadowColor: '#3E1F75', shadowOffset: {width: 0, height: 4}, shadowOpacity: 0.05, shadowRadius: 12, elevation: 2}, sectionTitle: {marginBottom: 12, color: '#28166F', fontSize: 15, fontWeight: '800'}, chips: {flexDirection: 'row', flexWrap: 'wrap', gap: 8}, chip: {minHeight: 44, justifyContent: 'center', borderWidth: 1, borderColor: '#E2D8F0', borderRadius: 15, backgroundColor: '#FBF9FD', paddingHorizontal: 14}, chipSelected: {borderColor: '#7046C2', backgroundColor: '#EFE6FA'}, chipText: {color: '#655A8D', fontSize: 13}, chipTextSelected: {color: '#5C32AE', fontWeight: '800'}, save: {height: 54, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', borderRadius: 18, backgroundColor: '#6942BD', shadowColor: '#5731A3', shadowOffset: {width: 0, height: 5}, shadowOpacity: 0.2, shadowRadius: 10, elevation: 4}, saveText: {marginLeft: 9, color: '#FFFFFF', fontSize: 16, fontWeight: '800'}, privacy: {flexDirection: 'row', justifyContent: 'center', alignItems: 'center', gap: 6, paddingVertical: 2}, privacyText: {color: '#756A8D', fontSize: 10}, pressed: {opacity: 0.82, transform: [{scale: 0.985}]}, disabled: {opacity: 0.55}, error: {color: '#A8505A', fontSize: 13, textAlign: 'center'}});
