import React, {useEffect, useRef} from 'react';
import {AccessibilityInfo, Animated, KeyboardAvoidingView, Platform, Pressable, SafeAreaView, ScrollView, StatusBar, StyleSheet, Text, View} from 'react-native';
import {MaterialDesignIcons} from '@react-native-vector-icons/material-design-icons';
import {useNavigation, type NavigationProp} from '@react-navigation/native';
import {useSafeAreaInsets} from 'react-native-safe-area-context';
import type {RootStackParamList} from '../../navigation/AppNavigator';

type Props = {title: string; icon: string; children: React.ReactNode; onSave: () => void; saving?: boolean; error?: string};

export function JournalScreenLayout({title, icon, children, onSave, saving, error}: Props): React.JSX.Element {
  const navigation = useNavigation<NavigationProp<RootStackParamList>>();
  const insets = useSafeAreaInsets();
  const entrance = useRef(new Animated.Value(0)).current;
  useEffect(() => {AccessibilityInfo.isReduceMotionEnabled().then(reduce => Animated.timing(entrance, {toValue: 1, duration: reduce ? 0 : 280, useNativeDriver: true}).start());}, [entrance]);
  const date = new Intl.DateTimeFormat('fr-FR', {weekday: 'long', day: 'numeric', month: 'long'}).format(new Date());
  return <SafeAreaView style={styles.safe}><StatusBar backgroundColor="#F8EFFF" barStyle="dark-content" /><KeyboardAvoidingView behavior={Platform.OS === 'ios' ? 'padding' : undefined} keyboardVerticalOffset={insets.top} style={styles.flex}><View style={styles.header}><Pressable accessibilityLabel="Retour" accessibilityRole="button" onPress={navigation.goBack} style={styles.back}><MaterialDesignIcons color="#6949BE" name="arrow-left" size={28} /></Pressable><View style={styles.headerCopy}><Text style={styles.title}>{title}</Text><Text style={styles.date}>{date}</Text></View><View style={styles.headerIcon}><MaterialDesignIcons color="#6949BE" name={icon as never} size={25} /></View></View><Animated.View style={[styles.flex, {opacity: entrance, transform: [{translateY: entrance.interpolate({inputRange: [0, 1], outputRange: [8, 0]})}]}]}><ScrollView contentContainerStyle={[styles.content, {paddingBottom: Math.max(insets.bottom, 16) + 30}]} keyboardShouldPersistTaps="handled" showsVerticalScrollIndicator={false}>{children}{error ? <Text accessibilityRole="alert" style={styles.error}>{error}</Text> : null}<Pressable accessibilityLabel="Enregistrer" accessibilityRole="button" disabled={saving} onPress={onSave} style={({pressed}) => [styles.save, pressed && styles.pressed, saving && styles.disabled]}><MaterialDesignIcons color="#FFFFFF" name="check-circle-outline" size={22} /><Text style={styles.saveText}>{saving ? 'Enregistrement…' : 'Enregistrer'}</Text></Pressable></ScrollView></Animated.View></KeyboardAvoidingView></SafeAreaView>;
}

export function SectionCard({title, children}: {title: string; children: React.ReactNode}) {return <View style={styles.section}><Text style={styles.sectionTitle}>{title}</Text>{children}</View>;}

export function ChoiceChips({options, value, values, onChange, multiple}: {options: string[]; value?: string; values?: string[]; onChange: (value: string) => void; multiple?: boolean}) {return <View style={styles.chips}>{options.map(option => {const selected = multiple ? values?.includes(option) : value === option; return <Pressable key={option} accessibilityRole={multiple ? 'checkbox' : 'radio'} accessibilityState={{checked: Boolean(selected)}} onPress={() => onChange(option)} style={({pressed}) => [styles.chip, selected && styles.chipSelected, pressed && styles.pressed]}><Text style={[styles.chipText, selected && styles.chipTextSelected]}>{option}</Text></Pressable>;})}</View>;}

const styles = StyleSheet.create({safe: {flex: 1, backgroundColor: '#F8EFFF'}, flex: {flex: 1}, header: {minHeight: 76, flexDirection: 'row', alignItems: 'center', paddingHorizontal: 14}, back: {width: 48, height: 48, alignItems: 'center', justifyContent: 'center'}, headerCopy: {flex: 1, marginLeft: 5}, title: {color: '#28166F', fontFamily: 'serif', fontSize: 25, fontWeight: '700'}, date: {marginTop: 2, color: '#655A8D', fontSize: 12}, headerIcon: {width: 44, height: 44, alignItems: 'center', justifyContent: 'center', borderRadius: 22, backgroundColor: '#EEE3FA'}, content: {padding: 16, paddingBottom: 30, gap: 13}, section: {borderWidth: 1, borderColor: 'rgba(105,73,190,0.12)', borderRadius: 23, backgroundColor: '#FFFDF9', padding: 15, elevation: 1}, sectionTitle: {marginBottom: 12, color: '#28166F', fontSize: 16, fontWeight: '700'}, chips: {flexDirection: 'row', flexWrap: 'wrap', gap: 8}, chip: {minHeight: 44, justifyContent: 'center', borderWidth: 1, borderColor: '#E2D8F0', borderRadius: 22, backgroundColor: '#F8F2FC', paddingHorizontal: 14}, chipSelected: {borderColor: '#6949BE', backgroundColor: '#EEE3FA'}, chipText: {color: '#655A8D', fontSize: 13}, chipTextSelected: {color: '#6949BE', fontWeight: '700'}, save: {height: 54, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', borderRadius: 18, backgroundColor: '#6949BE', elevation: 3}, saveText: {marginLeft: 9, color: '#FFFFFF', fontSize: 17, fontWeight: '700'}, pressed: {opacity: 0.82, transform: [{scale: 0.99}]}, disabled: {opacity: 0.55}, error: {color: '#A8505A', fontSize: 13, textAlign: 'center'}});
